---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   namespace: prod
#   labels:
#     app: nginx
# spec:
#   replicas: 0
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:bookworm
#           ports:
#             - containerPort: 80


apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx-rollout
  namespace: prod
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nginx-rollout
  spec:
      containers:
        - name: nginx
          image: nginx:bookworm
          ports:
            - containerPort: 80
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 1h
      - setWeight: 20
      - pause: {}
