---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
#   namespace: prod
#   labels:
#     app: nginx
# spec:
#   replicas: 0
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#         - name: nginx
#           image: nginx:bookworm
#           ports:
#             - containerPort: 80


apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: example-rollout
  namespace: prod
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:bullseye
        ports:
        - containerPort: 80
  minReadySeconds: 30
  revisionHistoryLimit: 3
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        args:
          - name: stable-hash
            valueFrom:
              podTemplateHashValue: Stable
          - name: latest-hash
            valueFrom:
              podTemplateHashValue: Latest
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 20
      - pause: {duration: 1m}
      - setWeight: 40
      - pause: {duration: 1m}
      - setWeight: 60
      - pause: {duration: 1m}
      - setWeight: 80
      - pause: {duration: 1m}
