apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: guestbook-ui
spec:
  replicas: 15
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
        name: guestbook-ui
        ports:
        - containerPort: 80
  minReadySeconds: 30
  strategy:
    canary:
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause:
          duration: 15s
      - setWeight: 20
      - pause:
          duration: 15s
      - setWeight: 50
      - pause: {}
