apiVersion: batch/v1
kind: Job
metadata:
  name: guestbook-ui
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: sleeper
          image: alpine
          imagePullPolicy: IfNotPresent
          command: [sleep]
          args:
            [
              "180"
            ]
      restartPolicy: Never
  backoffLimit: 1
